version: "3.8"

services:
  whisper-api:
    build: .
    container_name: whisper-api
    restart: unless-stopped
    ports:
      - "9000:9000"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whisper.rule=Host(`whisper.teastymenu.ru`)"
      - "traefik.http.routers.whisper.entrypoints=websecure"
      - "traefik.http.routers.whisper.tls.certresolver=myresolver"
      - "traefik.http.services.whisper.loadbalancer.server.port=9000"
    networks:
      - traefik

networks:
  traefik:
    external: true
